// Code generated by MockGen. DO NOT EDIT.
// Source: repository/currencyRepository.go

// Package repository is a generated GoMock package.
package repository

import (
	reflect "reflect"
	gomock "github.com/golang/mock/gomock"
)

// MockDynamoDBRepository is a mock of CurrencyRepository interface.
type MockDynamoDBRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDynamoDBRepositoryMockRecorder
}

// MockDynamoDBRepositoryMockRecorder is the mock recorder for MockDynamoDBRepository.
type MockDynamoDBRepositoryMockRecorder struct {
	mock *MockDynamoDBRepository
}

// NewMockDynamoDBRepository creates a new mock instance.
func NewMockDynamoDBRepository(ctrl *gomock.Controller) *MockDynamoDBRepository {
	mock := &MockDynamoDBRepository{ctrl: ctrl}
	mock.recorder = &MockDynamoDBRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDynamoDBRepository) EXPECT() *MockDynamoDBRepositoryMockRecorder {
	return m.recorder
}

// GetItem mocks base method.
func (m *MockDynamoDBRepository) GetItem(currency string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItem", currency)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItem indicates an expected call of GetItem.
func (mr *MockDynamoDBRepositoryMockRecorder) GetItem(currency interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItem", reflect.TypeOf((*MockDynamoDBRepository)(nil).GetItem), currency)
}

// UpdateItems mocks base method.
func (m *MockDynamoDBRepository) UpdateItems(newRates map[string]float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItems", newRates)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateItems indicates an expected call of UpdateItems.
func (mr *MockDynamoDBRepositoryMockRecorder) UpdateItems(newRates interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItems", reflect.TypeOf((*MockDynamoDBRepository)(nil).UpdateItems), newRates)
}